export const CHANGE_FILTER_TYPE = 'CHANGE_FILTER_TYPE';
export const CHANGE_SORTING_TYPE = 'CHANGE_SORTING_TYPE';
export const ADD_MOVIE = 'ADD_MOVIE';
export const REMOVE_MOVIE = 'REMOVE_MOVIE';
export const GET_FROM_STORAGE = 'GET_FROM_STORAGE';